title: "Ziyuan Tang"
description: "JUAN's Journey of Growth."
url: "https://52JUAN.github.io"
baseurl: ""

markdown: kramdown

# Keep it minimal for GitHub Pages
plugins: []

# Optional: reduce build noise
exclude:
  - README.md
  - .gitignore
